{% set name = "lightcurvelynx" %}
{% set version = "0.3.15" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lightcurvelynx-{{ version }}.tar.gz
  sha256: 79fea57f2592285a8a2c3d7fa09384fac306fbd96b373c0083149b342c944906

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - astroquery
    - cdshealpix
    - citation-compass >=0.0.3
    - matplotlib-base
    - mocpy
    - nested-pandas >=0.6
    - networkx
    - numpy >=2
    - pandas
    - pooch
    - PyYAML >=6
    - regions
    - scipy
    - tqdm

test:
  imports:
    - lightcurvelynx
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/lincc-frameworks/lightcurvelynx
  summary: 'A Fast and Nimble Package for Time Domain Astronomy'
  description: |
    LightCurveLynx aims to provide a flexible, scalable, and user-friendly time-domain
    simulation software with realistic effects and survey strategies. The software
    package consists of multiple stages: a flexible framework for consistently
    sampling model parameters, realistic models of time varying phenomena (such as
    supernovae and AGNs), effect models (such as dust extinction), and survey
    characteristics (such as cadence, filters, and noise).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremykubica
    - hombit
    - mi-dai
    - olivialynn
